### ISSUE TITLE
Sending >10 Second Snaps from Camera Roll

### ISSUE THREAD

**Issue by RevealedSoulEven** [rodit/SnapMod#121]
Actually when I try to send images from camera roll then it works and even it's fine. But for some videos it's not working maybe of different resolutions and it goes as a normal video. Any way to fix that? Because it's awful when sending that video to 100 people at once and it goes as a normal chat

**Comment by rodit** [comment]
Where are you sending the video from (within Snapchat or sharing from another app, if from Snapchat, where in the app)? How long is the video - try sending a short video (<10 seconds) and a long one (>10 seconds) to test if it's the length. I am able to send videos of all lengths to multiple recipients as snaps so I need as much info as possible to fix this.

Thanks

**Comment by tarek133** [comment]
It's the same for me. Trying to send a video which is longer than 10 seconds directly from snap memories, will result in nothing happening.

**Comment by rodit** [comment]
I have fixed this and will release an update later with other fixes too.

**Comment by rodit** [comment]
Fixed in v1.6.4

**Comment by RevealedSoulEven** [comment]
Yes now it's cool. Thanks @rodit

**Comment by Magna-Graecia** [comment]
> It's the same for me. Trying to send a video which is longer than 10 seconds directly from snap memories (tap on the send button), will result in nothing happening.

This still happens for me. Not sure if anyone else is experiencing this.

**Comment by Magna-Graecia** [comment]
@rodit I don't think he was saying that sending to multiple recipients at once was the problem. He was saying that sending live snaps in general works for images, but for some videos it doesn't work, which ends up being bad when he sends that video to 100 people only to find out that it got sent as a chat instead of a live snap.

**Comment by RevealedSoulEven** [comment]
@Magna-Graecia Actually you are right. I said that 100+ people are not the issue. The videos in the ratio of snapchat camera are sent directly as snaps. But whenever I send videos like 16:9 or 1:1 then they were being sent as normal videos.
But anyways now it's fixed in this update. So, no more issues😌
